<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diaporama"
    nsURI="www.ekaii.org" nsPrefix="org.ekaii">
  <eClassifiers xsi:type="ecore:EClass" name="SlideShow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AllSlides" lowerBound="1"
        upperBound="-1" eType="#//Slide" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FirstSlide" lowerBound="1"
        eType="#//Slide"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DefaultSlideDuration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClickSoundTimeout" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NextSlideActionType" lowerBound="1"
        eType="#//ActionTypeEnumSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PictureResizingPolicy"
        lowerBound="1" eType="#//PictureResizingPolicyType" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slide">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AutomaticNextSlide" eType="#//Slide"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SlideName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SoundPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PicturePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ClickedNextSlide" unique="false"
        eType="#//Slide"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClickedSlideSoundPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals name="MOUSE" literal="Souris"/>
    <eLiterals name="SPACE_BAR" value="1" literal="Barre d'espace"/>
    <eLiterals name="KEYBOARD" value="2" literal="Clavier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ActionTypeEnumSet" instanceTypeName="java.util.EnumSet&lt;org.ekaii.diaporama.ActionType>"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PictureResizingPolicyType">
    <eLiterals name="FIT"/>
    <eLiterals name="STRETCH" value="1"/>
  </eClassifiers>
</ecore:EPackage>
